/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Direccion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
         this.setLocationRelativeTo(null);

        Color colorFondo = new Color(188, 138, 243);
        this.jPanel2.setBackground(colorFondo);
    }
    
    public static boolean validarNumeroa(String cadena) {

        return cadena.matches("[0-9]");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Clave = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        txt_ApMa = new javax.swing.JTextField();
        txt_Folio = new javax.swing.JTextField();
        txt_ApPa = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        btn_Salir = new javax.swing.JButton();
        btn_CrearCorreo = new javax.swing.JButton();
        btn_CrearClaveUni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMBRE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setText("FOLIO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("AP-PATERNO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("AP-MATERNO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setText("CLAVE UNI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel6.setText("udelasalle.edu.mx");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel8.setText("CORREO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel2.add(txt_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 230, -1));
        jPanel2.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, -1));

        txt_ApMa.setText("Briones");
        jPanel2.add(txt_ApMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 176, -1));

        txt_Folio.setText("72806");
        jPanel2.add(txt_Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 176, -1));

        txt_ApPa.setText("Milian");
        jPanel2.add(txt_ApPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 176, -1));

        txt_Nombre.setText("Pablo");
        jPanel2.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 176, -1));

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        btn_CrearCorreo.setText("CREAR CORREO");
        btn_CrearCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CrearCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btn_CrearClaveUni.setText("CREAR CLAVE UNI");
        btn_CrearClaveUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearClaveUniActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CrearClaveUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_CrearCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearCorreoActionPerformed
        
        String nombre, folio, apellidoPaterno, apellidoMaterno;

        if (this.txt_Folio.getText().equals("") || this.txt_Nombre.getText().equals("") || this.txt_ApPa.getText().equals("") || this.txt_ApMa.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Llene todas las casillas.");

        } else if (!validarNumeroa(this.txt_Folio.getText().trim()) && this.txt_Folio.getText().length() != 5) {

            JOptionPane.showMessageDialog(null, "Introduce números | Introduce 5 dígitos");

            this.txt_Folio.setText("");

        } else {

            nombre = this.txt_Nombre.getText();
            folio = this.txt_Folio.getText();
            apellidoPaterno = this.txt_ApPa.getText();
            apellidoMaterno = this.txt_ApMa.getText();

            Direccion correo = new Direccion(folio, nombre, apellidoPaterno, apellidoMaterno);

            this.txt_Correo.setText(correo.getCorreo());

        }
        
    }//GEN-LAST:event_btn_CrearCorreoActionPerformed

    private void btn_CrearClaveUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearClaveUniActionPerformed
        
        String nombre, folio, apellidoPaterno, apellidoMaterno;

        if (this.txt_Folio.getText().equals("") || this.txt_Nombre.getText().equals("") || this.txt_ApPa.getText().equals("") || this.txt_ApMa.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Llene todas las casillas.");

        } else if (!validarNumeroa(this.txt_Folio.getText().trim()) && this.txt_Folio.getText().length() != 5) {

            JOptionPane.showMessageDialog(null, "Introduce números | Introduce 5 dígitos");

            this.txt_Folio.setText("");

        } else {

            nombre = this.txt_Nombre.getText().trim();
            folio = this.txt_Folio.getText().trim();
            apellidoPaterno = this.txt_ApPa.getText().trim();
            apellidoMaterno = this.txt_ApMa.getText().trim();

            Direccion clave = new Direccion(folio, nombre, apellidoPaterno, apellidoMaterno);

            this.txt_Clave.setText(clave.getClaveUni());

        }


        
    }//GEN-LAST:event_btn_CrearClaveUniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearClaveUni;
    private javax.swing.JButton btn_CrearCorreo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_ApMa;
    private javax.swing.JTextField txt_ApPa;
    private javax.swing.JTextField txt_Clave;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Folio;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
